### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by polux** [Levi-Lesches/dart-a-star#3]
I might be wrong but it seems to me the implemented algorithm (both for the 2d and generalized version) is not A*: a neighbor's tentative score should not only be updated if it is not yet in the open set, but also if the new tentative score is better.

In other words:

```
if (!candidate._isInOpenSet) {
```

should be 

```
if ((!candidate._isInOpenSet) || newF < candidate._f) {
```

If I'm not mistaken.

**Comment by Levi-Lesches** [comment]
Hi! How's your decade been? 

I took over this repo so I'm just looking at this now. 

I don't think this is needed? If a node A is opened after a node B, and A == B (meaning, A is in the open set as soon as it's being checked), then A's cost > B's cost. Basically, we should always be opening nodes in increasing order, so two identical nodes should never be opened where the second is cheaper than the first. 

Hope that helps! I'll close, but if I missed something definitely let me know.
